---
resources:
  - name: cli
    type: git
    source:
      uri: https://github.com/cloudfoundry/cli
      branch: vat
      ignore_paths: &ciPaths
        - bin
        - ci
        - integration
        - Makefile

  - name: cli-i18n
    type: git
    source:
      uri: https://github.com/cloudfoundry/cli-i18n
      branch: master

  - name: cli-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/cli
      branch: vat
      paths: *ciPaths

  - name: cf-cli-binaries
    type: s3
    source:
      bucket: ((staging-bucket-name))
      access_key_id: ((cli-team-aws-s3-access-key-id))
      secret_access_key: ((cli-team-aws-s3-secret-access-key))
      versioned_file: "v7/cf-cli-binaries.tgz"

  - name: cli-integration
    type: git
    source:
      uri: https://github.com/cloudfoundry/cli
      branch: vat
      paths:
        - integration

  - name: vars-store
    type: git
    source:
      uri: git@github.com:cloudfoundry/cli-private
      private_key: ((cli-private-github-private-key))
      branch: master

  - name: edge-osx-binary-64
    type: s3
    source:
      bucket: v7-cf-cli-releases
      access_key_id: ((cli-team-aws-s3-access-key-id))
      secret_access_key: ((cli-team-aws-s3-secret-access-key))
      versioned_file: master/cf-cli_edge_osx.tgz
      region_name: us-west-1

  - name: gcp-bosh-pool
    type: pool
    source:
      uri: git@github.com:cloudfoundry/cli-pools
      private_key: ((cli-pools-github-private-key))
      branch: master
      pool: mashed-potato

jobs:
  - name: units
    serial: true
    plan:
      - aggregate:
          - get: cli
            trigger: true
          - get: cli-ci
      - aggregate:
          - task: units-linux
            file: cli-ci/ci/cli-v7/tasks/units-linux.yml
          - task: units-osx
            file: cli-ci/ci/cli-v7/tasks/units-osx.yml
          - task: units-windows
            file: cli-ci/ci/cli-v7/tasks/units-windows.yml

  - name: build-binaries
    serial: true
    plan:
      - aggregate:
          - get: cli
            trigger: true
            passed: [units]
          - get: cli-ci
          - get: cli-i18n
      - task: build-i18n
        file: cli-ci/ci/cli/tasks/generate-i18n-resources.yml
      - task: build
        file: cli-ci/ci/cli/tasks/build-binaries.yml
      - put: cf-cli-binaries
        params:
          file: compiled/cf-cli-binaries.tgz

  - name: integration-linux
    serial: true
    plan:
      - aggregate:
          - get: cli
            passed: [build-binaries]
          - get: cf-cli-binaries
            passed: [build-binaries]
            trigger: true
          - get: cli-ci
          - get: cli-integration
          - get: vars-store
          - put: gcp-bosh-pool
            params:
              acquire: true
      - do:
          - task: cleanup-integration
            file: cli-ci/ci/cli/tasks/cleanup-integration.yml
            input_mapping:
              bosh-lite-lock: gcp-bosh-pool
          - task: integration
            file: cli-ci/ci/cli/tasks/integration-linux.yml
            input_mapping:
              bosh-lite-lock: gcp-bosh-pool
            ensure:
              task: cleanup-integration
              file: cli-ci/ci/cli/tasks/cleanup-integration.yml
              input_mapping:
                bosh-lite-lock: gcp-bosh-pool
            params: &integration_params
              CF_INT_CLIENT_ID: 'potato-face'
              CF_INT_CLIENT_SECRET: ((client-secret))
              CF_INT_DOCKER_IMAGE: ((dockerhub-private-image))
              CF_INT_DOCKER_USERNAME: ((dockerhub-username))
              CF_INT_DOCKER_PASSWORD: ((dockerhub-password))
              CF_INT_IGNORE_API_VERSION_CHECK: false
          - task: integration-experimental
            file: cli-ci/ci/cli/tasks/integration-experimental-linux.yml
            input_mapping:
              bosh-lite-lock: gcp-bosh-pool
            ensure:
              task: cleanup-integration
              file: cli-ci/ci/cli/tasks/cleanup-integration.yml
              input_mapping:
                bosh-lite-lock: gcp-bosh-pool
    ensure:
      put: gcp-bosh-pool
      params:
        release: gcp-bosh-pool

  - name: upload-binaries
    serial: true
    plan:
      - aggregate:
          - get: cli
            passed: [integration-linux]
          - get: cf-cli-binaries
            passed: [integration-linux]
            trigger: true
          - get: cli-ci
      - task: extract-binaries
        file: cli-ci/ci/cli/tasks/extract-binaries.yml
      - task: create-unix-installers
        file: cli-ci/ci/cli/tasks/create-installers.yml
      - task: package-binaries
        file: cli-ci/ci/cli/tasks/package-binaries.yml
      - put: edge-osx-binary-64
        params:
          file: archives/cf-cli_edge_osx.tgz
